### ISSUE TITLE
データ形式をmarkdownからCSVに変更する

### ISSUE THREAD

**Issue by sachin21** [jitomesky/jitome_database#2]
CSVとしてデータが少ない今の段階からデータ形式変えとくと後々databaseにぶち込む時に楽かもですね。
GitHubはCSVの表示も出来るので見ることにも困らないかと。

**Comment by jitomesky** [comment]
c18cc4fad486ddbb59bae6b5a92c313167336c6c で対応しました。
ありがとうございます!

**Comment by sachin21** [comment]
👍
